language: node_js

addons:
  apt:
    packages:
      - xvfb

install:
  - export DISPLAY=':99.0'
  - Xvfb :99 -screen 0 1024x768x24 > /dev/null 2>&1 &

node_js:
  - "6"
  - "node"

env:
  - FORMDATA_VERSION=1.0.0
  - FORMDATA_VERSION=2.1.0

before_script:
  - 'if [ "$FORMDATA_VERSION" ]; then npm install form-data@^$FORMDATA_VERSION; fi'

before_install: npm install -g npm

script: npm run report

cache:
  directories:
    - node_modules
